name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: "161.97.136.42"
          username: "sergio"
          key: |
            -----BEGIN OPENSSH PRIVATE KEY-----
            b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
            QyNTUxOQAAACCS/JDD7DBwBfe93B+Wrej2oUOjzvdaIRH41zo4eMr6twAAAJiZDE+MmQxP
            jAAAAAtzc2gtZWQyNTUxOQAAACCS/JDD7DBwBfe93B+Wrej2oUOjzvdaIRH41zo4eMr6tw
            AAAEBm8gEm7SrW0r/Jne0eTnf22T64Sx6evPS2Uux6ywaBTJL8kMPsMHAF973cH5at6Pah
            Q6PO91ohEfjXOjh4yvq3AAAAEXNlcmdpb0B2bWkzMjQwNjQwAQIDBA==
            -----END OPENSSH PRIVATE KEY-----
          script: |
            if [ ! -d "/home/sergio/Plataforma-SaaS-Multi-tenant" ]; then
              git clone https://github.com/SAOT31/Plataforma-SaaS-Multi-tenant.git /home/sergio/Plataforma-SaaS-Multi-tenant
            fi
            cd /home/sergio/Plataforma-SaaS-Multi-tenant
            git fetch --all
            git reset --hard origin/main
            
            # Create .env file for production
            echo "GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }}" > .env
            echo "POSTGRES_DB=pqrs_saas" >> .env
            echo "POSTGRES_USER=postgres" >> .env
            echo "POSTGRES_PASSWORD=postgrespassword" >> .env
            
            docker compose down
            docker compose up --build -d
